name: PR Review with AI
on:
  pull_request_target:
    types: [opened]
permissions: write-all

jobs:
  review:
    runs-on: ubuntu-latest
    steps:



      - id: model
        name: Get model name
        uses: sergeysova/jq-action@v2
        with:
          cmd: 'curl "https://openai.lipinski.app/v1/models" | jq ".data[].id" | cut -c2- | rev | cut -c2- '

      - name: Run PR Review
        uses: mi4uu/mi4uloper@master
        with:
          chat-token: "${{ steps.model.outputs.value }}"
          base-url: "https://openai.lipinski.app/v1"
          model: "${{ steps.model.outputs.value }}"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
