name: PR Review with local pr
on:
  pull_request:
permissions: write-all
jobs:
  review:
    env:
        ACTIONS_RUNNER_DEBUG: true
        ACTIONS_STEP_DEBUG: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: co
        run: git pull ${{ github.repository }} ${{ github.event.pull_request.base.ref }}

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install
      - name: wanna know
        run: git config --global --add safe.directory .
      - name: yyyls
        run: ls
      - id: model
        name: Get model name
        uses: sergeysova/jq-action@v2
        with:
          cmd: 'curl "https://openai.lipinski.app/v1/models" | jq ".data[].id" | cut -c2- | rev | cut -c2- '

      - name: Run PR Review
        uses: mi4uu/mi4uloper@master
        with:
          chat-token: "${{ steps.model.outputs.value }}"
          base-url: "https://openai.lipinski.app/v1"
          model: "${{ steps.model.outputs.value }}"
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
            ACTIONS_RUNNER_DEBUG: true
          
