name: PR Review with local
on:
  push:

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install
      - name: wanna know
        run: which git
      - id: model
        name: Get model name
        uses: sergeysova/jq-action@v2
        with:
          cmd: 'curl "https://openai.lipinski.app/v1/models" | jq ".data[].id" | cut -c2- | rev | cut -c2- '

      - name: Run PR Review
        uses: mi4uu/mi4uloper@master
        with:
          chat-token: "${{ steps.model.outputs.value }}"
          base-url: "https://openai.lipinski.app/v1"
          model: "${{ steps.model.outputs.value }}"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
